# Generated by Django 3.2.5 on 2022-06-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('instruction', models.TextField()),
                ('cook_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(related_name='recipe', to='cookbook.Ingredients')),
                ('tags', models.ManyToManyField(related_name='recipe', to='cookbook.Tags')),
            ],
        ),
        migrations.AlterField(
            model_name='pictures',
            name='recipie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cookbook.recipe'),
        ),
        migrations.DeleteModel(
            name='Recipie',
        ),
    ]
