# Generated by Django 3.2.5 on 2022-06-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20220602_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
